### PR TITLE
finish doneCb before waitForResult returns

### LINKED ISSUE #155: `waitForResult` returns before doneCb
In simpleActionClient `waitForResult` sometimes waits until the done-callback was called, but it should ensure its completion to avoid race-conditions on the client side.

See ros-planning/moveit#1493

Steps to reproduce see [docker gist](https://gist.github.com/jschleicher/3e10e85c1a88e979bdfa4b4e04013046)
1. start from [actionlib_tutorials](https://github.com/ros/common_tutorials.git)
2. add sleep to `doneCb` in `fibonacci_callback_client`
3. call `waitForResult` in main
4. See debug output showing that `waitForResult` returned before `doneCb` is done

### PR DESCRIPTION
**Pull request by jschleicher**
Fixes #155

~Is `indigo-devel` the correct branch? Or should this be targeted to noetic to avoid breaking old use-cases?~

### CODE REVIEW

File: include/actionlib/client/simple_action_client.h [hunk 1]
```diff
@@ -535,15 +535,15 @@ void SimpleActionClient<ActionSpec>::handleTransition(GoalHandleT gh)
...
           {
             boost::mutex::scoped_lock lock(done_mutex_);
             setSimpleState(SimpleGoalState::DONE);
           }
 
-          if (done_cb_) {
-            done_cb_(getState(), gh.getResult());
-          }
-
           done_condition_.notify_all();
```
Comment (rhaschke) [inline include/actionlib/client/simple_action_client.h]: To be honest, I don't think there is an issue in actionlib:
Actually, done-callbacks might expect that the current state is indeed `DONE` when they are called (I would do so).
The done_condition_.notify_all() ensures that threads waiting on this condition are only woke up when both the state changed and the callback was executed. So, from my point of view, everything is fine here.
I think we have another issue in MoveIt.

Comment (jschleicher) [reply include/actionlib/client/simple_action_client.h]: @rhaschke Please see the docker container in #155 to reproduce the actionlib issue from the actionlib_tutorials. To check `ros::ok()` the thread is woken up every 0.1 seconds so it doesn't wait for the notification:
https://github.com/ros/actionlib/blob/c89e440519eeb88a5005065a32330655c9450b8e/include/actionlib/client/simple_action_client.h#L602-L603

I agree, that the client could expect the goal state to be `DONE`, ~~so the fix isn't that simple...~~ edit: and it actually is.

Comment (rhaschke) [reply include/actionlib/client/simple_action_client.h]: Thanks @jschleicher for this clarification! This was the point I was missing.
Probably, there should be an extra flag in actionlib that eventually indicates the `DONE` state - after the `done_cb_` was executed.
Great error analysis by the way!

Comment (jschleicher) [reply include/actionlib/client/simple_action_client.h]: I've added a test to check `getState()` inside the callback. The state returned there is based on comm_state_:
https://github.com/ros/actionlib/blob/c89e440519eeb88a5005065a32330655c9450b8e/include/actionlib/client/simple_action_client.h#L346
So I still propose the original fix.

**Comment by jschleicher** [comment]
@mjcarroll Please review.
And also have a look at #150 which fixes the same problem in the python client.

File: include/actionlib/client/simple_action_client.h (hunk 1 above)
Comment (Dale-Koenig) [reply include/actionlib/client/simple_action_client.h]: > To be honest, I don't think there is an issue in actionlib:
> Actually, done-callbacks might expect that the current state is indeed `DONE` when they are called (I would do so).
> The done_condition_.notify_all() ensures that threads waiting on this condition are only woke up when both the state changed and the callback was executed. So, from my point of view, everything is fine here.
> I think we have another issue in MoveIt.

Couldn't there be spurious wakeups either way?

Comment (jschleicher) [reply include/actionlib/client/simple_action_client.h]: > Couldn't there be spurious wakeups either way?

Yes, but the check of `cur_simple_state_` is still false in case of a spurious wake-up, so the loop continues: https://github.com/ros/actionlib/blob/c89e440519eeb88a5005065a32330655c9450b8e/include/actionlib/client/simple_action_client.h#L592

Comment (jschleicher) [reply include/actionlib/client/simple_action_client.h]: Note that this PR is not about race-conditions or unstable timing, but the attached test-case *reliably fails* without the fix.

**Comment by mjcarroll** [comment]
@jschleicher  Looks good, but  please retarget to `noetic-devel`.

**Comment by jschleicher** [comment]
@mjcarroll Thank you! I've rebased onto noetic-devel.

**Comment by mjcarroll** [comment]
@ros-pull-request-builder retest this please

**Comment by jschleicher** [comment]
@mjcarroll The tests are still unstable, which seems to be an occurrence of https://github.com/ros/actionlib/issues/119#issuecomment-595713144. Adding a delay time after `waitForServer()` does fix the tests, but we would have to introduce it into every single test case.

File: actionlib/test/simple_client_test.cpp [hunk 2]
```diff
@@ -104,18 +98,21 @@ TEST(SimpleClient, easy_callback)
   bool started = client.waitForServer(ros::Duration(10.0));
   ASSERT_TRUE(started);
 
+  // sleep a bit to make sure that all topics are properly connected to the server.
+  ros::Duration(0.01).sleep();
```
Comment (fujitatomoya) [inline actionlib/test/simple_client_test.cpp:102]: i believe this should be done by waitForServer.

File: actionlib/test/simple_client_test.cpp [hunk 3]
```diff
@@ -79,23 +79,17 @@ TEST(SimpleClient, easy_tests) {
...
+  EXPECT_TRUE(ac->getState() == SimpleClientGoalState::SUCCEEDED)
+    << "Expected [SUCCEEDED], but getState() returned [" << ac->getState().toString() << "]";
   EXPECT_TRUE(state == SimpleClientGoalState::SUCCEEDED)
     << "Expected [SUCCEEDED], but goal state is [" << state.toString() << "]";
-}
-
-void easyOldDoneCallback(bool * called, const TerminalState & terminal_state,
-  const TestResultConstPtr &)
-{
+  ros::Duration(0.1).sleep();
```
Comment (fujitatomoya) [inline actionlib/test/simple_client_test.cpp:89]: what is this duration for?

File: actionlib/test/simple_client_test.cpp (hunk 2 above)
Comment (jschleicher) [reply actionlib/test/simple_client_test.cpp:102]: Yep, it should. But actually it isn't, see my comment above: https://github.com/ros/actionlib/pull/156#issuecomment-595713514

File: actionlib/test/simple_client_test.cpp (hunk 3 above)
Comment (jschleicher) [reply actionlib/test/simple_client_test.cpp:89]: It's a callback, that takes some time and gives execution back to the main thread in the mean time. Without the fix, this test case `easy_callback` fails.

Comment (jschleicher) [reply actionlib/test/simple_client_test.cpp:89]: See also reproduction step 2. in #155.

File: actionlib/test/simple_client_test.cpp (hunk 2 above)
Comment (fujitatomoya) [reply actionlib/test/simple_client_test.cpp:102]: i understand this is just a work-around to pass the test, but even with this duration SimpleClientFixture fails with server state is still ACTIVE (expected to be SUCCESS). so I expect this additional duration is not needed.

Comment (jschleicher) [reply actionlib/test/simple_client_test.cpp:102]: It's the unrelated test file `exercise_simple_client.cpp` that fails - adding another sleep over there would help.
```
[actionlib.rosunit-test_cpp_simple_client/just_succeed][FAILURE]
 /tmp/ws/src/actionlib/actionlib/test/exercise_simple_client.cpp:72
```

**Review by fujitatomoya — APPROVED** [review]
LGTM

**Comment by v4hn** [comment]
@mjcarroll: @jschleicher continuously provided feedback on this for over four months now,
the only test that fails is not related to his patch but to a racing condition to setup a topic connection in time and it fixes a long-standing issue we have to work around in MoveIt.

It would be great to see this merged and released in noetic (and best-case also a backport to melodic, but at this point I would be happy to see this merged in any branch)!

**Comment by mjcarroll** [comment]
@v4hn Yes, I appreciate the iteration from @jschleicher.

At this point, I think it's acceptable to land on `noetic`, and I would be happy to review a backport to `melodic`

**Comment by mjcarroll** [comment]
@ros-pull-request-builder retest this please

**Comment by mjcarroll** [comment]
> @mjcarroll The tests are still unstable, which seems to be an occurrence of #119 (comment). Adding a delay time after waitForServer() does fix the tests, but we would have to introduce it into every single test case.

@jschleicher Do you want to do this in a follow up PR?

**Review by mjcarroll — APPROVED** [review]
